name: table_entry
description: "Spables - speech to tables."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: '>=3.4.4 <4.0.0'

icons_launcher:
  image_path: "assets/images/Logo.png"
  adaptive_background_image: "assets/images/Logo.png"
  adaptive_background_color: "8332ac"
  adaptive_foreground_image: "assets/images/Logo.png"
  
  platforms:
    android:
      enable: true
    ios:
      enable: true

dependencies:
  another_audio_recorder: ^1.2.1
  another_flushbar: ^1.12.30
  csv: ^6.0.0
  custom_pop_up_menu: ^1.2.4
  dropdown_button2: ^2.3.9
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  flutter_sound: ^9.17.6
  flutter_translate: ^4.1.0
  geolocator: ^13.0.1
  haptic_feedback: ^0.5.1+1
  hexcolor: ^3.0.1
  http: ^1.2.2
  hugeicons: ^0.0.7
  icons_launcher: ^3.0.0
  intl: ^0.19.0
  mic_stream: ^0.7.1+2
  noise_meter: ^5.0.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  restart_app: ^1.3.2
  scroll_snap_list: ^0.9.1
  share_plus: ^10.0.2
  socket_io_client: ^3.0.2
  sound_stream: ^0.4.1
  url_launcher: ^6.3.0
  waveform_flutter: ^1.0.1
  weather: ^3.1.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/i18n/

  fonts: 
    - family: WorkSans
      fonts:
        - asset: assets/font/static/WorkSans-Medium.ttf

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-SemiBold.ttf
