name: table_entry
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  custom_pop_up_menu: ^1.2.4
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  haptic_feedback: ^0.5.1+1
  hexcolor: ^3.0.1
  hugeicons: ^0.0.7
  mic_stream: ^0.7.1+2
  noise_meter: ^5.0.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  speech_to_text: ^6.6.2
  waveform_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts: 
    - family: WorkSans
      fonts:
        - asset: assets/font/static/WorkSans-Medium.ttf

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-SemiBold.ttf