name: table_entry
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hexcolor: ^3.0.1
  mic_stream: ^0.7.1+2
  noise_meter: ^5.0.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  speech_to_text: ^6.6.2
  waveform_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
