name: spables
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependency_overrides:
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/
    - assets/i18n/

  fonts: 
    - family: WorkSans
      fonts:
        - asset: assets/font/static/WorkSans-Medium.ttf

  uses-material-design: true


dependencies:

  another_flushbar: ^1.12.30
  audio_session: ^0.1.21
  csv: ^6.0.0
  custom_pop_up_menu: ^1.2.4
  dropdown_button2: ^2.3.9
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  flutter_translate: ^4.1.0
  geolocator: ^13.0.1
  haptic_feedback: ^0.5.1+1
  hexcolor: ^3.0.1
  http: ^1.2.2
  hugeicons: ^0.0.7
  icons_launcher: ^3.0.0
  intl: ^0.19.0
  mic_stream: ^0.7.1+2
  noise_meter: ^5.0.2
  path_provider: ^2.1.4
  provider: ^6.1.2
  record: ^5.2.0
  restart_app: ^1.3.2
  scroll_snap_list: ^0.9.1
  share_plus: ^10.0.2
  socket_io_client: ^3.0.2
  url_launcher: ^6.3.0
  waveform_flutter: ^1.0.1
  weather: ^3.1.1
  web_socket_channel: ^3.0.1
  flutter_sound: ^9.17.8


