name: table_entry
description: "Spables  hexcolor: ^3.0.1
  http: ^1.5.0
  hugeicons: 0.0.7
  icons_launcher: ^3.0.3pe  sha  waveform_flutter: ^1.2.0
  weather: ^3.2.1
  web_socket_channel: ^3.0.3plus: ^12.0.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2 to tables."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.4+7

environment:
  sdk: '>=3.4.4 <5.0.0'

icons_launcher:
  image_path: "assets/images/Logo.png"
  adaptive_background_image: "assets/images/Logo.png"
  adaptive_background_color: "8332ac"
  adaptive_foreground_image: "assets/images/Logo.png"
  
  platforms:
    android:
      enable: true
    ios:
      enable: true

dependencies:
  another_flushbar: ^1.12.32
  audio_session: ^0.2.2
  csv: ^6.0.0
  custom_pop_up_menu: ^1.2.4
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  flutter_translate: ^4.1.0
  geolocator: ^14.0.2
  haptic_feedback: ^0.5.1+1
  hexcolor: ^3.0.1
  http: ^1.5.0
  hugeicons: ^1.1.1
  icons_launcher: ^3.0.3
  noise_meter: ^5.1.0
  path_provider: ^2.1.4
  provider: ^6.1.5+1
  record: ^6.1.2
  restart_app: ^1.3.2
  scroll_snap_list: ^0.9.1
  share_plus: ^12.0.0
  socket_io_client: ^3.1.2
  url_launcher: ^6.3.2
  waveform_flutter: ^1.2.0
  weather: ^3.2.1
  web_socket_channel: ^3.0.3
  opus_flutter: ^3.0.1
  opus_dart: ^3.0.1
  flutter_background: ^1.3.0+1
  flutter_foreground_task: ^9.1.0
  audioplayers: ^6.5.1
  onnxruntime: ^1.4.1  # May need manual library alignment

dependency_overrides:
  ffi: ^2.1.4 # resolve conflict with opus_dart in favor of opus
  intl: ^0.20.0
  hugeicons: 0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/i18n/
    - assets/models/silero_vad_legacy.onnx
    - assets/models/silero_vad_v5.onnx

  fonts: 
    - family: WorkSans
      fonts:
        - asset: assets/font/static/WorkSans-Medium.ttf

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-SemiBold.ttf
